### ISSUE TITLE
Сверстать таблицу событий

### ISSUE THREAD

**Issue by secmon** [SviatoslavTaranenko/graylog2-react-ui#1]
В общем напомню - ты делаешь веб-морду для вывода и поиска по событиям как у системы централизованного сбора событий (логов) graylog2.

Событие состоит из:
* идентификатора (уникальный номер события из букв и цифр)
* множества пар поле-значение, например:
** facility = user-level
** program = target
** timestamp = 2022-12-17 19:38:35.530 +04:00 (время поступления события в систему)
** message = "139963890829056 INFO  [activationValidator, 368] Leave Validate. Succeeded for integrity.VcIntegrity.retrieveHostIPAddresses on target: Integrity.VcIntegrity"
** и других

Для просмотра событий - они выводятся в виде таблиц. Столбцы - это поля события - столбцы можно выводить в таблицу и скрывать из нее, менять местами, сортировать.
Каждая строчка таблицы (кроме заголовка) - это отдельное событие. На него можно нажать и событие раскроется - будут видны все поля.

Твоя первая задача - сверстать таблицу с событиями как тут (только выделенную красным часть):
<img width="1377" alt="Снимок экрана 2022-12-17 в 18 40 22" src="https://user-images.githubusercontent.com/1040449/208250567-03d93abb-b360-4249-9d06-7531c2d56f84.png">

Никакие раскрываемости строк, динамические элементы и прочее делать не надо - просто страничка серого фона с таблицей - как в красном прямоугольнике. Левое вертикальное меню тоже не нужно. События для таблицы придумай сам. Границы таблицы радиусные. Отступ от границ таблицы до границ страницы - пикселей 5 наверно

Результат должен быть в виде:
* HTML файла index.html
* img/ - папка с картинками (иконками)
* css/ - папка с css

Заметь, что поле message -  оно выводится какбы ниже самих полей и другим цветом и шрифтом. Поле со временем - полужирное.

Таблица должна расширяться по размеру экрана.

Как подсказка - в оригинальном грейлоге  собственно табличная часть внутри таблицы событий - это table.

Вот еще пара скриншотов (на будущее и для понимания)

<img width="1373" alt="Снимок экрана 2022-12-17 в 18 42 16" src="https://user-images.githubusercontent.com/1040449/208250078-3594cd5a-70ae-4d89-b9c1-19a0b0f82820.png">
<img width="1375" alt="Снимок экрана 2022-12-17 в 18 47 08" src="https://user-images.githubusercontent.com/1040449/208250079-951533e5-8d32-4139-b369-12b75c87c428.png">

**Comment by secmon** [comment]
А где код? по ссылке https://github.com/SviatoslavTaranenko/graylog2-react-ui пусто - выгрузи результат, чтобы можно было посмотреть

**Comment by SviatoslavTaranenko** [comment]
Привет, код есть, у меня есть поблема с таблицей, никак не могу зделать одну штуку и ещё не могу загрузить код, сейчас пробую разобратся. Как загружу, увидешь мою ошибку в коде.

**Comment by SviatoslavTaranenko** [comment]
Загрузил.

**Comment by secmon** [comment]
Ну как я вижу - основная проблема, что у тебя несогласованы ширины столбцов строки заголовка (серые) и столбцов в строках данных (событиях). При этом по сути таблицы - ширины столбов должны быть адаптивны размеру данных в них (типовое поведение таблицы в браузерах) - обрати внимание на то что я написал в подсказке:

_Как подсказка - в оригинальном грейлоге собственно табличная часть внутри таблицы событий - это table._

У тебя должна быть одна таблица - где заголовок (thead + tr + th) - это серая часть на скрине - а строки - это собственно данные (tbody + tr + td) - но все это должно быть сделано в пределах одной общей таблицы - <table>. По строкам данных - там собственно у каждого сообщения должна быть 1 строка со столбами и вторая строка с сообщением (синим)

Для решения вопроса как сделать строку с сообщением - она объединяет там несколько столбов в один - погугли каким образом в html можно объединить несколько td в один - решение буквалько в 1 атрибуте 

Переверстывай с учетом указанной информации и выкладывай обнову

И переоткрой эту задачу - закроешь как я ее приму (как заказчик) - как переверстаешь - выдам еще замечания

**Comment by secmon** [comment]
Разумеется таблица - это только часть с событиями, а "All messages" и верхние иконки - это вне table.

**Comment by SviatoslavTaranenko** [comment]
Принял, спасибо, сделаю.

**Comment by SviatoslavTaranenko** [comment]
Привет, перезалил верстку.

**Comment by secmon** [comment]
Следующие замечания:

1) ширины столбов у тебя какие-то фиксированные - при изменении ширины окна таблица должна адаптироваться к его ширине - вот 2 примера для пояснения
<img width="1440" alt="Снимок экрана 2023-01-08 в 17 24 53" src="https://user-images.githubusercontent.com/1040449/211201781-61d7fd50-e275-4093-8e75-3dfc866aa52c.png">
<img width="1440" alt="Снимок экрана 2023-01-08 в 17 25 39" src="https://user-images.githubusercontent.com/1040449/211201788-ed8d5824-a19b-4ee4-9580-f2345f3c941f.png">

сделай чтобы оно все адаптировалось (вообще это базовое свойство таблицы - подбирать ширину столба при изменении размера таблицы)


2) шрифт в заголовках таблицы и в полях (кроме message) у тебя отличается от шрифта в message - сделай чтобы шрифт был как в message (не цвет, а сам шрифт - сейчас там на times new roman похож)


3) отсутствует вертикальный скроллинг событий - посмотри на скрин - там где события
<img width="1440" src="https://user-images.githubusercontent.com/1040449/208250567-03d93abb-b360-4249-9d06-7531c2d56f84.png">

Видишь - блок, обведенный красным - он фиксированной высоты (померь по скрину и задай столько же) - а событий в нем явно больше чем 1 экран и справа от них (внутри красного блока) есть скроллинг

Сделай также - там идея типа высота этого блока красного фиксированная и если надо ее изменить - то надо потянуть вниз за такую маленькую стрелочку справа внизу (это на потом задача будет - там JS нужен будет)

4) Вокруг блока, который ты верстаешь - есть серая граница - у тебя просто белый блок. Также есть граница под заголовком - выделил на скрине зеленым
<img width="1440" alt="Снимок экрана 2023-01-08 в 17 39 23" src="https://user-images.githubusercontent.com/1040449/211202493-400bd007-9e99-4c68-bfa3-012998f9926f.png">

5) Цвет фона и цвет строки заголовка таблицы у тебя разве соответствует скрину-образцу? Там помоему другой серый оттенок


PS - когда тебя просят сверстать чтото - надо делать как можно более похоже на образец - цвета - отступы - на реальной работе тебе дадут макет какой-нибудь в фотошопе (или в чем там их сейчас делают) и надо будет делать пиксель в пиксель

**Comment by SviatoslavTaranenko** [comment]
Привет, у нас сейчас большие проблемы со светом, его почти нет целый день, не могу пока сделать код, когда, будет возможность, обязательно скину.

**Comment by SviatoslavTaranenko** [comment]
Привет, сегодня немного есть возможность поработать , 4 часа есть свет😂,
Подскажи пожалуйста, какой шрифт используется и какой цвет фона и верха таблицы

**Comment by SviatoslavTaranenko** [comment]
Обновил документ, использовал: font-family: 'Open Sans', sans-serif; 
Мне по буквах он. Цвет на глаз определял.
Жду замечаний, спасибо.

**Comment by secmon** [comment]
блин пропустил письмо - ты мне для оперативности пиши плз в скайп или вайбер... если я не отвечаю/ ща смотрю

**Comment by secmon** [comment]
шрифты

all messages
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
rgb (31, 31,31)
font-size: 1.125rem;
computed font-size: 15.75px



time
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 1rem;
computed font-size: 14px
font-weight: bold


blue text line
font-size: 0.889rem;
font-family: "Roboto Mono", Menlo, Monaco, Consolas, "Courier New", monospace;
    color: rgb(0, 87, 168);
computed font-size: 12.446px


header and fields values
font-size: 0.889rem;
color: rgb(31, 31, 31);
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

**Comment by secmon** [comment]
Вот что я вижу сейчас:
<img width="1440" alt="Снимок экрана 2023-01-22 в 18 31 43" src="https://user-images.githubusercontent.com/1040449/213924306-ba1ed5ee-41ae-4e7f-bd53-c5ec1a2b29ec.png">

Старые  замечания:
1. Принято. Стало лучше. По нюансу с изменяемым числом столбцов - скажу позже, когда будем автоматизировать интерфейс

2. Шрифты скинул в сообщении выше - подправь

3. Смотри - у тебя справа от блока с событиями нету отступа - скроллинг залез прямо на границу белого блока и даже правый нижний угол вместо закругленного стал прямоугольным. Слева у тебя отступ есть - а справа и снизу -- нет -- сделай - на исходном скрине задачи все есть. 

4. Ты не сделал границы. Цвет бордюра с закругленными углами - rgb(208, 208, 208); Цвет нижнего бордюра у заголовков полей -  rgb(128,128,128)

5. Цвет фона страницы: rgb(232, 232, 232); Цвет th - rgb(230, 230, 230);

**Comment by SviatoslavTaranenko** [comment]
Подправил и обновил файл. Смотри.
Извини что не могу быстро делать роботу, зависит когда нам дают свет.

**Comment by secmon** [comment]
Старые замечания:

2. Принято
3. Принято

4. Нету бордюра у полоски с заголовками полей - нижний бордюр в 1 пиксель - не вижу - цвет задан - а толщина как будто нет

5. Принято

Новые замечания и доработки:

6. Кнопки сверху переделай чтобы они были как на исходном скрине - ты их как будто перерисовал чтоли. Плюс они должны при наведении выделяться как на скринах, указатель мышки должен становиться в виде указательного пальца (как при наведении на ссылки), а также должны показываться подписи - посмотри на одном из скринов есть (слева направо): 

Compress with
Focus this widget
Edit
Open actions dropdown


<img width="1350" alt="Снимок экрана 2023-01-23 в 16 38 26" src="https://user-images.githubusercontent.com/1040449/214056318-5940e630-a141-4fa3-a431-3eff9f59049e.png">

<img width="1294" alt="Снимок экрана 2023-01-23 в 16 39 03" src="https://user-images.githubusercontent.com/1040449/214056322-6f40fa73-4d9c-4b60-881d-686f0f94c8c2.png">

<img width="1374" alt="Снимок экрана 2023-01-23 в 16 39 38" src="https://user-images.githubusercontent.com/1040449/214056324-08c49289-6a3e-4515-869c-f213f1ef946f.png">
<img width="1347" alt="Снимок экрана 2023-01-23 в 16 40 28" src="https://user-images.githubusercontent.com/1040449/214056328-0c75881e-540a-4587-99e2-d3f423126363.png">


<img width="1368" alt="Снимок экрана 2023-01-23 в 16 37 10" src="https://user-images.githubusercontent.com/1040449/214056297-1dc1a84d-e1c1-4790-9ebe-545cde8c9f6e.png">


7. Левая иконка - рядом с All messages должна во первых быть как на скрине исходном (серой), при наведении курсор должен становиться как при перетягивании (крест такой)

**Comment by secmon** [comment]
8. Есть 2 состояния столбцов - по нему сейчас произведена сортировка (сейчас такое tmestamp - она более черная), а у остальных - более серая. Также при наведении на название заголовка столбца и иконку - курсор должен быть как для ссылок (палец). При этом в на остальной части th курсор должен быть обычный. В будущем по клику на название столбца будет сортировка применяться

**Comment by SviatoslavTaranenko** [comment]
Привет, файл обновил. Только подскажи как поменять цвет иконки на серый. (не скачивать, а в css)

**Comment by secmon** [comment]
Старые замечания

4) Принято

6) Плюс тут же отвечу на твой вопрос - про фон. Короче в исходном грейлоге картинки все в svg - тегами хтмл прям - я все скопировал их код - скорее всего должно его хватить. Про фон думаю теперь догадаться несложно


```
<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="bars" class="svg-inline--fa fa-bars fa-w-14 WidgetHeader__WidgetDragHandle-ps4vrl-3 iFYFkJ widget-drag-handle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg>


<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="compress" class="svg-inline--fa fa-compress fa-w-14 " role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M436 192H312c-13.3 0-24-10.7-24-24V44c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v84h84c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm-276-24V44c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v84H12c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h124c13.3 0 24-10.7 24-24zm0 300V344c0-13.3-10.7-24-24-24H12c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h84v84c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-84h84c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12H312c-13.3 0-24 10.7-24 24v124c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12z"></path></svg>

<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="expand-arrows-alt" class="svg-inline--fa fa-expand-arrows-alt fa-w-14 " role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M448 344v112a23.94 23.94 0 0 1-24 24H312c-21.39 0-32.09-25.9-17-41l36.2-36.2L224 295.6 116.77 402.9 153 439c15.09 15.1 4.39 41-17 41H24a23.94 23.94 0 0 1-24-24V344c0-21.4 25.89-32.1 41-17l36.19 36.2L184.46 256 77.18 148.7 41 185c-15.1 15.1-41 4.4-41-17V56a23.94 23.94 0 0 1 24-24h112c21.39 0 32.09 25.9 17 41l-36.2 36.2L224 216.4l107.23-107.3L295 73c-15.09-15.1-4.39-41 17-41h112a23.94 23.94 0 0 1 24 24v112c0 21.4-25.89 32.1-41 17l-36.19-36.2L263.54 256l107.28 107.3L407 327.1c15.1-15.2 41-4.5 41 16.9z"></path></svg>

<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="edit" class="svg-inline--fa fa-edit fa-w-18 " role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M402.6 83.2l90.2 90.2c3.8 3.8 3.8 10 0 13.8L274.4 405.6l-92.8 10.3c-12.4 1.4-22.9-9.1-21.5-21.5l10.3-92.8L388.8 83.2c3.8-3.8 10-3.8 13.8 0zm162-22.9l-48.8-48.8c-15.2-15.2-39.9-15.2-55.2 0l-35.4 35.4c-3.8 3.8-3.8 10 0 13.8l90.2 90.2c3.8 3.8 10 3.8 13.8 0l35.4-35.4c15.2-15.3 15.2-40 0-55.2zM384 346.2V448H64V128h229.8c3.2 0 6.2-1.3 8.5-3.5l40-40c7.6-7.6 2.2-20.5-8.5-20.5H48C21.5 64 0 85.5 0 112v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V306.2c0-10.7-12.9-16-20.5-8.5l-40 40c-2.2 2.3-3.5 5.3-3.5 8.5z"></path></svg>


<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-down" class="svg-inline--fa fa-chevron-down fa-w-14 " role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-testid="widgetActionDropDown"><path fill="currentColor" d="M207.029 381.476L12.686 187.132c-9.373-9.373-9.373-24.569 0-33.941l22.667-22.667c9.357-9.357 24.522-9.375 33.901-.04L224 284.505l154.745-154.021c9.379-9.335 24.544-9.317 33.901.04l22.667 22.667c9.373 9.373 9.373 24.569 0 33.941L240.971 381.476c-9.373 9.372-24.569 9.372-33.942 0z"></path></svg>

<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="sort-amount-up" class="svg-inline--fa fa-sort-amount-up fa-w-16 " role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M304 416h-64a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h64a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16zM16 160h48v304a16 16 0 0 0 16 16h32a16 16 0 0 0 16-16V160h48c14.21 0 21.38-17.24 11.31-27.31l-80-96a16 16 0 0 0-22.62 0l-80 96C-5.35 142.74 1.77 160 16 160zm416 0H240a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h192a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16zm-64 128H240a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h128a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16zM496 32H240a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h256a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16z"></path></svg>

<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="sort-amount-up" class="svg-inline--fa fa-sort-amount-up fa-w-16 " role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M304 416h-64a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h64a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16zM16 160h48v304a16 16 0 0 0 16 16h32a16 16 0 0 0 16-16V160h48c14.21 0 21.38-17.24 11.31-27.31l-80-96a16 16 0 0 0-22.62 0l-80 96C-5.35 142.74 1.77 160 16 160zm416 0H240a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h192a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16zm-64 128H240a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h128a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16zM496 32H240a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h256a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16z"></path></svg>
```


7) Тут как в 6 - также иконку приложил (первая вроде бы) - замени

8) Ты не понял - при наведении толщина столба не меняется - меняется при смене столба, по которому идет сортировка. Т.е. со штампом времени должен быть жирным (текущий столбец - по которому сейчас отсортировано) - как без наведения мышки так и без наведения, а остальные - нежирные. При этом курсор меняется у всех столбов (как и сейчас сделано). 
И еще - я неправильно наверно донес мысль - вот то расстояние между названием столбца (facility например) и иконкой сортировки в этом столбце- оно тоже должно быть частью - при наведении на которую курсор меняется - это типа такая большая кнопка одна - название + иконка

**Comment by SviatoslavTaranenko** [comment]
Обновил, но не могу разобраться как зафиксировать одно название и переключать, также  не могу поставить чтобы название и иконка вместе меняли цвет.
Всё остальное сделавл

**Comment by secmon** [comment]
задачу принял, можешь закрывать
