### ISSUE TITLE
Переверстать таблицу событий - с использованием классов (БЭМ или чтото на подобии)

### ISSUE THREAD

**Issue by secmon** [SviatoslavTaranenko/graylog2-react-ui#2]
<img width="1440" alt="Снимок экрана 2023-01-28 в 12 14 20" src="https://user-images.githubusercontent.com/1040449/215258109-940a43d3-5174-4565-870c-8219bf354a7d.png">
<img width="1440" alt="Снимок экрана 2023-01-28 в 12 14 54" src="https://user-images.githubusercontent.com/1040449/215258111-65991bca-762d-4f9c-9110-d0e549407174.png">

Заметил что ты не используешь возможности css по унификации и сокращению кода - использования классов именно как классы - а не идентификаторы. Типа

```
.thead .timespamp {
    font-weight: 100;
    width: 43%;
    text-align: left;
}

.thead .facility {
    font-weight: 100;
    width: 18%;
    text-align: left;
}

.thead .level {
    font-weight: 100;
    width: 18%;
    text-align: left;
}
```

Ты многократно дублируешь один и тот же код. В коде выше по сути ты описываешь столбцы таблицы событий. 

Можно описать один абстрактный класс типа column-header и добавить его к каждому столбцу в его классы внутри HTML (было `<th class="facility">`, стало `<th class="column-header facility">`). И код сократится в разы и будет гораздо поддерживаемым и будет отражать семантику.

```
.thead .column-header {
    font-weight: 100;
    text-align: left;
}

.thead .timespamp {
    width: 43%;
}

.thead .facility {
    width: 18%;
}

.thead .level {
    width: 18%;
}
```

Собственно задача: изучи что такое БЭМ или другую методологию по использованию классов CSS именно как классов, выдели одинаковые сущности и сократи код - чтобы было меньше дублирования. Для информации - вот тот самый большой белый прямоугольник с закругленными углами - это называется в грейлоге widget (их на странице может быть много и разных - с таблицами, с графиками) - это возможно тебе понадобится для использования в именовании классов в БЭМ

**Comment by SviatoslavTaranenko** [comment]
Хорошо.

**Comment by SviatoslavTaranenko** [comment]
Привет, переверстал.

**Comment by secmon** [comment]
Да, стало лучше, но некоторые моменты

1 - Почему ты используешь такие длинные пути в CSS? В БЭМ разве не идея в том, чтобы в описании стилей пути к элементу были как можно более короткие - и именно по этому идет такое впихивание структуры в само название класса

Т.е. вместо
```
.container .widget .widget_table .widget_table_all .widget_table_all_thead .widget_table_all_thead_title {
    font-weight: 100;
    text-align: left;
}
```

разве не надо писать просто?
```
.widget_table_all_thead_title {
    font-weight: 100;
    text-align: left;
}
```
Суть БЭМ (насколько мне помнится - как я немного смотрел про него лет 10 назад ) в том числе чтобы чтобы ускорить рендеринг. Типа 
```
.container .widget .widget_table .widget_table_all .widget_table_all_thead .widget_table_all_thead_title_timespamp
```
Отрисовывается гораздо дольше, чем 
```
.widget_table_all_thead_title_timespamp
```
Т.к. браузер при отрисовке проходится по описанию строчки в CSS справа налево - и типа сначала выберет все .widget_table_all_thead_title_timespamp, потом оставит только те, которые внутри .widget_table_all_thead и т.д. Что уж говорить о конструкциях вида .container `.widget .widget_table .widget_table_all .widget_table_all_thead .widget_table_all_thead_title_timespamp div ` - тут вообще он начнет выбирать все div-ы и т.д.

Разберись с этим моментом. Вроде как элементов HTML (... div,  ... span) быть не должно вообще в стилях по БЭМ (могу ошибаться)

2 - .widget_table_all_thead_title
по ВЭМ насколько я смотрел - другая схема именования - вроде через 2 подчеркивания или через 2 минуса? Раз у тебя таких классов нет - значит ты чтото делаешь неправильно? (насчет этого я не уверен - изучи сам поподробней)

3 - Посмотри на поля событий
```
                            <td class="widget_table_all_tbody_list_timespamp">2023-01-01 08:06:48 +02:00</td>
                            <td class="widget_table_all_tbody_list">user-level</td>
                            <td class="widget_table_all_tbody_list">5</td>
```
По сути ты в CSS сейчас дублируешь описание widget_table_all_tbody_list и widget_table_all_tbody_list_timespamp. Т.е. у тебя есть блок (? не уверен что правильно говорю) и есть модификатор (другой стиль чуть чуть у того же семантического блока - что то столбец, что другое - столбец). Разве с точки зрения БЭМ не нужно было сделать код 
```
                            <td class="widget_table_all_tbody_list widget_table_all_tbody_list_timespamp">2023-01-01 08:06:48 +02:00</td>
                            <td class="widget_table_all_tbody_list">user-level</td>
                            <td class="widget_table_all_tbody_list">5</td>
```
И в .widget_table_all_tbody_list_timespamp описании описать только отличия от .widget_table_all_tbody_list ?
Помоему идея как раз такая у БЭМ

Дополняю: 
Про .widget_header_icon_menu такая же тема. У тебя есть "иконка в хидере" .widget_header_icon. И по всей логике - левая кннка бутерброд тоже должна быть "иконкой в хидере", но с модификатором (например "menu"): class="widget_header_icon widget_header_icon_menu"


4 - widget_table_all_tbody_list_timespamp - если я правильно понимаю - описание сущностей в БЭМ должно быть отвязано от HTML-структуры. Ты по идее должен описывать семантику = суть, а не использовать в стилях конкретные теги типа "tbody". Наверное более корректно было бы называть "body" или типа того. 

---


Вроде я +- попадаю в принципы
https://ru.bem.info/methodology/css/#%D0%BA%D0%B0%D0%BA-%D0%BF%D0%B5%D1%80%D0%B5%D0%B9%D1%82%D0%B8-%D0%BD%D0%B0-css-%D0%BF%D0%BE-%D0%B1%D1%8D%D0%BC

**Comment by secmon** [comment]
5 - И вообще по семантике. У нас есть:
- события (event/events)
- у событий есть поля (field/fields) 
- у полей есть ключи (keys/key или название поля name/names) - например, "facility" - и значения (value/values) - например "5"

Мне кажется было бы корректнее использовать такие семантически корректные слова в названиях классов. А не list, sublist

**Comment by secmon** [comment]
6 - widget_table_all_tbody_sublist - по сути это тоже как и в замечании 3 - тоже должен быть сделан как widget_table_all_tbody_list (этим словом у тебя обозначается "значение поля") + класс модификатор. Как мне кажется так семантически более корректно/ Это по сути тоже поле-значение- просто оно отличается по стилю

**Comment by secmon** [comment]
Не знаю приходит ли тебе оповещение об изменениях - я коммент https://github.com/SviatoslavTaranenko/graylog2-react-ui/issues/2#issuecomment-1418193955 подправил немного

**Comment by secmon** [comment]
Дополнил замечание 3 другим примером

**Comment by secmon** [comment]
Кстати - называй коммиты как-то более осмысленно
https://github.com/SviatoslavTaranenko/graylog2-react-ui/commits/main

У тебя там везде "add files via upload". Название коммита должно как-то характеризовать суть изменений в паре слов. Так это принято делать - в дельнейшем чтобы +- понимать что произошло глядя на историю коммитов.

**Comment by SviatoslavTaranenko** [comment]
Обновил модификаторы

**Comment by secmon** [comment]
1)

все таки как я писал ранее - с точки зрения БЭМ надо делать не так:
```
<tr class="table__tbody_list">
                            <td class="table__tbody_list_event">2023-01-01 07:59:52 +02:00</td>
                            <td class="table__tbody_list_user-level">user-level</td>
                            <td class="table__tbody_list_value">5</td>
                            <td class="table__tbody_list_target">target</td>
                        </tr>
```

А так:
```
<tr>
                            <td class="table__tbody_list table__tbody_list_event">2023-01-01 07:59:52 +02:00</td>
                            <td class="table__tbody_list">user-level</td>
                            <td class="table__tbody_list">5</td>
                            <td class="table__tbody_list">target</td>
                        </tr>
```
С соответствующей корректировкой CSS-стилей. Разве нет?

То есть основной стиль table__tbody_list  и его модификатор table__tbody_list_event

**Comment by SviatoslavTaranenko** [comment]
Обновил классы.
Да, так лучше видно где работает CSS

**Comment by secmon** [comment]
перепроверь код - сейчас у тебя "побеждает" не тот стиль - не синий текст в сообщении получился

<img width="1440" alt="Снимок экрана 2023-04-27 в 11 07 46" src="https://user-images.githubusercontent.com/1040449/234800241-501f05c1-a88c-41e8-9c8c-7e06f289afa1.png">

плюс время не полужирное

**Comment by SviatoslavTaranenko** [comment]
Подкоректировал

**Comment by secmon** [comment]
> Обновил классы. Да, так лучше видно где работает CSS

в thead_name - то же самое про классы поправь

**Comment by secmon** [comment]
принято - остались некоторые моменты- потом озвучу в рамках других задач
