### ISSUE TITLE
Сверстать развернутое событие

### ISSUE THREAD

**Issue by secmon** [SviatoslavTaranenko/graylog2-react-ui#3]
<img width="1373" alt="208250078-3594cd5a-70ae-4d89-b9c1-19a0b0f82820" src="https://user-images.githubusercontent.com/1040449/234823380-2b7f2a97-d058-4a55-81ad-4d37bb8a6e25.png">

при нажатии на таблице с событиями - в реальном грейлоге выбранное событие развертывается - как на скрине

пока без всякой автоматизации (без развертываний по клику) сверстай чтобы одно из событий было бы развернутым - как на скрине

какое-нибудь посередине списка

все делать в том же index.html

**Comment by SviatoslavTaranenko** [comment]
Сверстал поле событий, цвет брал тот как в других частях таблицы, одно меня смущает цвет текста в кнопках. Стрелки в кнопках я добавил как картинки, а не select.

**Comment by SviatoslavTaranenko** [comment]
Стрелки в кнопках я добавил как картинки, а не <select>.

**Comment by secmon** [comment]
**Замечание 1 (принято)**

Принцип БЭМ - чтобы не писать в стилях такую цепочку в CSS
`.widget__table .table__tbody .table__windows_object .table__windows_body .table__windows_body_information .table__windows_body_information_data {}`

Я уже расписывал про скорость рендеринга

Поправь в соответствии с принципами БЭМ **везде** (не только на этом стиле)

В теории у тебя тут например максимум должно остаться
`.widget__table .table__windows_body_information_data {}`

или вообще
`.table__windows_body_information_data {}`

Уже подумай сам в зависимости от названий

**Comment by secmon** [comment]
**Замечание 2**

Почему у меня твои полужирные стили в названии полей развернутого события и в названии полей в сайдбаре слева какие-то не полужиные? Сравни с исходным скрином

<img width="1440" alt="Снимок экрана 2023-05-06 в 11 07 21" src="https://user-images.githubusercontent.com/1040449/236611930-133503a4-5b63-41ee-9f4c-6d0d12d960b5.png">

Штамп времени в событиях - тоже какойто нежирный

**Comment by secmon** [comment]
**Замечание 3 (принято)**

Отступ между синей вертикальной полосой и текстом на скрине больше и приятней чем у тебя - увеличь

Отступ перед названием поля (над словом "facility" - и другими названиями полей) сделай больше - чтобы был как после значения поля

<img width="1440" alt="Снимок экрана 2023-05-06 в 11 11 31" src="https://user-images.githubusercontent.com/1040449/236612163-73f417da-820d-4d46-b065-3b59909c54f2.png">

**Comment by secmon** [comment]
**Замечание 4 (принято)**

Поправь везде "timespamp" на "timestamp"

**Comment by SviatoslavTaranenko** [comment]
Подправил. Изменил на timestamp но indexs обновлю позже, ошибку выдает

**Comment by secmon** [comment]
**Замечание 5**

Едет верстка в сафари

Испытай свою верстку в разных браузерах (посмотри как это делается)

<img width="1440" alt="Снимок экрана 2023-05-07 в 12 50 41" src="https://user-images.githubusercontent.com/1040449/236670619-f82d3024-9160-4188-8f09-ef9f47d2a1dd.png">

**Comment by secmon** [comment]
**Замечание 6**

поменяй шрифты

В развернутом событии у значений полей шрифт "Roboto Mono", Menlo, Monaco, Consolas, "Courier New", monospace; (12.446px)

Остальные шрифты везде "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif; 12.446px

All messages - 15.75px

b2d7... - 19.936px

**Comment by secmon** [comment]
К замечанию2 - ничего не изменилось у меня - поменяй шрифты и в хроме посмотри у себя

**Comment by SviatoslavTaranenko** [comment]
Шрифты поменял, в хром у меня все выглядит как на скрине

**Comment by secmon** [comment]
принято, завтра посмотрю что дальше - сделаю задачи
